# MPlayer input control file for Funkey-S

RIGHT       seek  +5
LEFT        seek  -5
UP          volume  +1
DOWN        volume  -1
BACKSPACE   seek    -60
TAB         seek    +60
ESC         quit
SPACE       pause
ENTER       pause
LCTRL       mute
LALT        cycle_audio
