name: fkgpiod Build

on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/FunKey-Project/fkgpiod.git
  REPO_BRANCH: main
  PKG_NAME: fkgpiod
  EXTRA_NAME_1: gmenu2x
  EXTRA_NAME_2: retroarch
  EXTRA_NAME_3: SDL2-30-10
  DIY_SH: configs/diy.sh
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: false
  TZ: Asia/Shanghai
  
jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: Initialization environment
      run: |
        sudo apt-get update
        sudo apt-get install -y -q --no-install-recommends build-essential make cmake wget autogen autoconf automake -y
        sudo apt-get -y autoremove
        sudo apt-get -y clean
        sudo rm -rf /var/lib/apt/lists/*
        sudo sed -i 's/# \(en_US.UTF-8\)/\1/' /etc/locale.gen
        sudo locale-gen --purge --lang en_US.UTF-8
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        
    - name: Clone source code
      working-directory: /workdir
      run: |
        df -hT $PWD
        mkdir -p ${PKG_NAME}/$EXTRA_NAME_3
        git clone $REPO_URL -b $REPO_BRANCH --depth 1 $PKG_NAME
        git clone https://github.com/FunKey-Project/gmenu2x.git -b FunKey --depth 1 ${PKG_NAME}/$EXTRA_NAME_1
        git clone https://github.com/libretro/RetroArch.git -b master --depth 1 ${PKG_NAME}/$EXTRA_NAME_2
        ln -sf /workdir/$PKG_NAME $GITHUB_WORKSPACE/$PKG_NAME
        cd && wget https://github.com/junfeng142/Demo-project/releases/download/2025.01.21-2345/FunKey-sdk-2.3.0.tar.gz
        cd && tar xvf FunKey-sdk-2.3.0.tar.gz
        sudo mv FunKey-sdk-2.3.0 /opt

    - name: Load custom configuration
      run: |
        mv configs/$PKG_NAME.* $PKG_NAME/
        mv configs/$EXTRA_NAME_1.* $PKG_NAME/$EXTRA_NAME_1/
        mv configs/$EXTRA_NAME_2.* $PKG_NAME/$EXTRA_NAME_2/
        mv configs/$EXTRA_NAME_3.* $PKG_NAME/$EXTRA_NAME_3/ && mv tools/*.tar.gz $PKG_NAME/$EXTRA_NAME_3/
        cd $PKG_NAME && patch -p1 < $PKG_NAME.patch
        cd $EXTRA_NAME_1 && patch -p1 < $EXTRA_NAME_1.patch
        cd ../$EXTRA_NAME_2 && patch -p1 < $EXTRA_NAME_2.patch
        cd ../$EXTRA_NAME_3 
        mkdir -p SDL2/ opengl/
        tar -zxvf SDL2.tar.gz -C SDL2/
        tar -zxvf opengl.tar.gz -C opengl/
        wget https://github.com/libsdl-org/SDL/releases/download/release-2.30.10/SDL2-2.30.10.tar.gz
        tar xvf SDL2-2.30.10.tar.gz
        patch -p1 < $EXTRA_NAME_3.patch
        sudo mv SDL2/ opengl/ /opt

    - name: Compile the firmware
      id: compile
      run: |
        cd $PKG_NAME && make
        cd $EXTRA_NAME_1 && chmod +x ./build.sh
        ./build.sh
        cd ../$EXTRA_NAME_2 && make -f Makefile.miyoo
        cd ../$EXTRA_NAME_3 && make SDL2_cfg
        make SDL2
        echo "status=success" >> $GITHUB_OUTPUT
        echo "DEVICE_NAME=$PKG_NAME" >> $GITHUB_ENV
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Check space usage
      if: (!cancelled())
      run: df -hT

    - name: Organize files
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        /opt/FunKey-sdk-2.3.0/bin/arm-funkey-linux-gnueabihf-strip ${PKG_NAME}/${PKG_NAME} -o $PKG_NAME/_opk/${PKG_NAME}
        /opt/FunKey-sdk-2.3.0/bin/arm-funkey-linux-gnueabihf-strip ${PKG_NAME}/${EXTRA_NAME_1}/${EXTRA_NAME_1} -o $PKG_NAME/_opk/${EXTRA_NAME_1}
        /opt/FunKey-sdk-2.3.0/bin/arm-funkey-linux-gnueabihf-strip ${PKG_NAME}/${EXTRA_NAME_2}/${EXTRA_NAME_2} -o $PKG_NAME/_opk/${EXTRA_NAME_2}
        /opt/FunKey-sdk-2.3.0/bin/arm-funkey-linux-gnueabihf-strip ${PKG_NAME}/${EXTRA_NAME_3}/build/.libs/libSDL2-2.0.so.0.3000.10 -o $PKG_NAME/_opk/libSDL2-2.0.so.0.3000.10
        cd $PKG_NAME/_opk
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT
        
    - name: Upload firmware directory
      uses: actions/upload-artifact@main
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: ${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}
        
    - name: Generate release tag
      id: tag
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
        echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
        touch release.txt
        echo "status=success" >> $GITHUB_OUTPUT
        
    - name: Upload firmware to release
      uses: softprops/action-gh-release@v1
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/*.opk
