name: EMU-OPK Build

on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/jbanes/rs97-dosbox.git
  REPO_BRANCH: master
  PKG_NAME: dosbox
  EXTRA_NAME_1: fba
  EXTRA_NAME_2: gngeo
  EXTRA_NAME_3: pcsx
  EXTRA_NAME_4: jvm
  EXTRA_NAME_5: vbemu
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: false
  TZ: Asia/Shanghai
  
jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: Initialization environment
      run: |
        sudo apt-get update
        sudo apt-get install -y -q --no-install-recommends build-essential make cmake wget autogen autoconf automake -y
        sudo apt-get -y autoremove
        sudo apt-get -y clean
        sudo rm -rf /var/lib/apt/lists/*
        sudo sed -i 's/# \(en_US.UTF-8\)/\1/' /etc/locale.gen
        sudo locale-gen --purge --lang en_US.UTF-8
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        
    - name: Clone source code
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone $REPO_URL -b $REPO_BRANCH --depth 1 $PKG_NAME
        git clone https://github.com/junfeng142/Demo-project.git -b fba --depth 1 ${PKG_NAME}/$EXTRA_NAME_1
        git clone https://github.com/junfeng142/Demo-project.git -b gngeo --depth 1 ${PKG_NAME}/$EXTRA_NAME_2
        git clone https://github.com/junfeng142/Demo-project.git -b pcsx-miyoo --depth 1 ${PKG_NAME}/$EXTRA_NAME_3
        git clone https://github.com/junfeng142/Demo-project.git -b jvm --depth 1 ${PKG_NAME}/$EXTRA_NAME_4
        git clone https://github.com/gameblabla/vbemu.git -b master --depth 1 ${PKG_NAME}/$EXTRA_NAME_5
        ln -sf /workdir/$PKG_NAME $GITHUB_WORKSPACE/$PKG_NAME
        cd && wget https://github.com/junfeng142/Demo-project/releases/download/2025.01.21-2345/FunKey-sdk-2.3.0.tar.gz
        cd && tar xvf FunKey-sdk-2.3.0.tar.gz
        sudo mv FunKey-sdk-2.3.0 /opt

    - name: Load custom configuration
      run: |
        mkdir -p $PKG_NAME/_opk && mv applications/$PKG_NAME/* $PKG_NAME/_opk
        mkdir -p $PKG_NAME/$EXTRA_NAME_1/_opk && mv applications/$EXTRA_NAME_1/* $PKG_NAME/$EXTRA_NAME_1/_opk
        mkdir -p $PKG_NAME/$EXTRA_NAME_2/_opk && mv applications/$EXTRA_NAME_2/* $PKG_NAME/$EXTRA_NAME_2/_opk
        mkdir -p $PKG_NAME/$EXTRA_NAME_3/_opk && mv applications/$EXTRA_NAME_3/* $PKG_NAME/$EXTRA_NAME_3/_opk
        mkdir -p $PKG_NAME/$EXTRA_NAME_4/_opk && mv applications/$EXTRA_NAME_4/* $PKG_NAME/$EXTRA_NAME_4/_opk
        mkdir -p $PKG_NAME/$EXTRA_NAME_5/_opk && mv applications/$EXTRA_NAME_5/* $PKG_NAME/$EXTRA_NAME_5/_opk
        cd $PKG_NAME && mv _opk/fit_for_dosbox_build.patch ./
        patch -p1 < fit_for_dosbox_build.patch
        cd $EXTRA_NAME_5 &&  mv _opk/fit_for_vbemu_build.patch ./
        patch -p1 < fit_for_vbemu_build.patch

    - name: Compile the firmware
      id: compile
      run: |
        export PATH=/opt/FunKey-sdk-2.3.0/bin/:$PATH
        cd $PKG_NAME/$PKG_NAME
        ./gcw0.sh
        make -j1 V=s
        cd ../$EXTRA_NAME_1
        make -j1 V=s
        cd ../$EXTRA_NAME_2
        make -j1 V=s
        cd ../$EXTRA_NAME_3
        make -j1 V=s
        cd ../$EXTRA_NAME_4 && chmod +x ./build.sh
        ./build.sh
        cd ../$EXTRA_NAME_5
        make -f Makefile.funkey
        echo "status=success" >> $GITHUB_OUTPUT
        echo "DEVICE_NAME=$PKG_NAME" >> $GITHUB_ENV
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Check space usage
      if: (!cancelled())
      run: df -hT

    - name: Organize files
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        /opt/FunKey-sdk-2.3.0/bin/arm-funkey-linux-gnueabihf-strip ${PKG_NAME}/dosbox/src/${PKG_NAME} -o $PKG_NAME/_opk/${PKG_NAME}
        /opt/FunKey-sdk-2.3.0/bin/arm-funkey-linux-gnueabihf-strip ${PKG_NAME}/${EXTRA_NAME_1}/bin/${EXTRA_NAME_1} -o ${PKG_NAME}/${EXTRA_NAME_1}/_opk/${EXTRA_NAME_1}
        /opt/FunKey-sdk-2.3.0/bin/arm-funkey-linux-gnueabihf-strip ${PKG_NAME}/${EXTRA_NAME_2}/${EXTRA_NAME_2} -o ${PKG_NAME}/${EXTRA_NAME_2}/_opk/${EXTRA_NAME_2}
        /opt/FunKey-sdk-2.3.0/bin/arm-funkey-linux-gnueabihf-strip ${PKG_NAME}/${EXTRA_NAME_3}/${EXTRA_NAME_3} -o ${PKG_NAME}/${EXTRA_NAME_3}/_opk/${EXTRA_NAME_3}
        cp ${PKG_NAME}/${EXTRA_NAME_4}/dist/microbackend.jar ${PKG_NAME}/${EXTRA_NAME_4}/_opk/dist/
        /opt/FunKey-sdk-2.3.0/bin/arm-funkey-linux-gnueabihf-strip ${PKG_NAME}/${EXTRA_NAME_5}/vb -o ${PKG_NAME}/${EXTRA_NAME_5}/_opk/vb
        tools/mksquashfs $PKG_NAME/_opk/* $PKG_NAME/${PKG_NAME}_funkey-s.opk -all-root -no-xattrs -noappend -no-exports
        rm -rf $PKG_NAME/_opk/* && mv $PKG_NAME/${PKG_NAME}_funkey-s.opk $PKG_NAME/_opk/
        tools/mksquashfs ${PKG_NAME}/${EXTRA_NAME_1}/_opk/* $PKG_NAME/_opk/${EXTRA_NAME_1}_funkey-s.opk -all-root -no-xattrs -noappend -no-exports
        tools/mksquashfs ${PKG_NAME}/${EXTRA_NAME_2}/_opk/* $PKG_NAME/_opk/${EXTRA_NAME_2}_funkey-s.opk -all-root -no-xattrs -noappend -no-exports
        tools/mksquashfs ${PKG_NAME}/${EXTRA_NAME_3}/_opk/* $PKG_NAME/_opk/${EXTRA_NAME_3}_funkey-s.opk -all-root -no-xattrs -noappend -no-exports
        tools/mksquashfs ${PKG_NAME}/${EXTRA_NAME_4}/_opk/* $PKG_NAME/_opk/${EXTRA_NAME_4}_funkey-s.opk -all-root -no-xattrs -noappend -no-exports
        tools/mksquashfs ${PKG_NAME}/${EXTRA_NAME_5}/_opk/* $PKG_NAME/_opk/${EXTRA_NAME_5}_funkey-s.opk -all-root -no-xattrs -noappend -no-exports
        cd $PKG_NAME/_opk
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT
        
    - name: Upload firmware directory
      uses: actions/upload-artifact@main
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: ${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}
        
    - name: Generate release tag
      id: tag
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
        echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
        touch release.txt
        echo "status=success" >> $GITHUB_OUTPUT
        
    - name: Upload firmware to release
      uses: softprops/action-gh-release@v1
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/*.opk
