name: Game-BIN Build

on:
  workflow_dispatch:

env:
  PKG_NAME: jinyong
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: false
  TZ: Asia/Shanghai
  
jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: Initialization environment
      run: |
        sudo apt-get update
        sudo apt-get install -y -q --no-install-recommends build-essential make cmake wget autogen autoconf automake p7zip-full -y
        sudo apt-get -y autoremove
        sudo apt-get -y clean
        sudo rm -rf /var/lib/apt/lists/*
        sudo sed -i 's/# \(en_US.UTF-8\)/\1/' /etc/locale.gen
        sudo locale-gen --purge --lang en_US.UTF-8
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        
    - name: Clone source code
      working-directory: /workdir
      run: |
        df -hT $PWD
        mkdir -p $PKG_NAME
        wget https://github.com/steward-fu/website/releases/download/miyoo/src_jinyong.7z
        7za x src_jinyong.7z
        ln -sf /workdir/$PKG_NAME $GITHUB_WORKSPACE/$PKG_NAME
        cd && wget https://github.com/steward-fu/nds_miyoo/releases/download/assets/toolchain.tar.gz
        cd && tar xvf toolchain.tar.gz
        sudo mv mmiyoo /opt
        sudo mv prebuilt /opt
        sudo rm /opt/mmiyoo/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/liblua.so

    - name: Load custom configuration
      run: |
        cd $PKG_NAME && mkdir -p _opk
        mv $GITHUB_WORKSPACE/applications/$PKG_NAME/$PKG_NAME.patch ./
        mv $GITHUB_WORKSPACE/applications/$PKG_NAME/* ./_opk
        wget https://www.lua.org/ftp/lua-5.1.5.tar.gz
        tar xvf lua-5.1.5.tar.gz

    - name: Compile the firmware
      id: compile
      run: |
        cd $PKG_NAME && patch -p1 < $PKG_NAME.patch
        chmod +x ./*.sh
        ./build.sh
        echo "status=success" >> $GITHUB_OUTPUT
        echo "DEVICE_NAME=$PKG_NAME" >> $GITHUB_ENV
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Check space usage
      if: (!cancelled())
      run: df -hT

    - name: Organize files
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        cd $PKG_NAME/_opk
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT
        
    - name: Upload firmware directory
      uses: actions/upload-artifact@main
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: ${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}
        
    - name: Generate release tag
      id: tag
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
        echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
        touch release.txt
        echo "status=success" >> $GITHUB_OUTPUT
        
    - name: Upload firmware to release
      uses: softprops/action-gh-release@v1
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/*.opk
