name: Game-OPK Build

on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/junfeng142/Demo-project.git
  REPO_BRANCH: sdlpal
  PKG_NAME: sdlpal
  REPOS: games/games.txt
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: false
  TZ: Asia/Shanghai
  
jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: Initialization environment
      run: |
        sudo apt-get update
        sudo apt-get install -y -q --no-install-recommends build-essential make cmake wget autogen autoconf automake -y
        sudo apt-get -y autoremove
        sudo apt-get -y clean
        sudo rm -rf /var/lib/apt/lists/*
        sudo sed -i 's/# \(en_US.UTF-8\)/\1/' /etc/locale.gen
        sudo locale-gen --purge --lang en_US.UTF-8
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        
    - name: Clone source code
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone $REPO_URL -b $REPO_BRANCH --depth 1 $PKG_NAME
        ln -sf /workdir/$PKG_NAME $GITHUB_WORKSPACE/$PKG_NAME
        while IFS='|' read -r repo_name url branch; do
        [[ -z "$repo_name" || "$repo_name" =~ ^# ]] && continue
        target_dir="${PKG_NAME}/${repo_name}"
        git clone -b "$branch" "$url" "$target_dir"
        done < "$GITHUB_WORKSPACE/$REPOS"
        cd && wget https://github.com/steward-fu/nds_miyoo/releases/download/assets/toolchain.tar.gz
        cd && tar xvf toolchain.tar.gz
        sudo mv mmiyoo /opt
        sudo mv prebuilt /opt

    - name: Load custom configuration
      run: |
        cd $PKG_NAME
        for dir in */ ; do
        dir_name="${dir%/}"
        mkdir -p $dir_name/_opk && mv $GITHUB_WORKSPACE/games/$dir_name/* $dir_name/_opk
        cd $dir_name && mv _opk/$dir_name.patch ./
        patch -p1 < $dir_name.patch
        chmod +x ./*.sh
        cd ..
        done

    - name: Compile the firmware
      id: compile
      run: |
        cd $PKG_NAME && mkdir -p _opk
        for dir in */ ; do
        dir_name="${dir%/}"
        [ -d $dir_name ] && cd "$dir_name"
        [ -e build_opk.sh ] && ./build_opk.sh
        done
        echo "status=success" >> $GITHUB_OUTPUT
        echo "DEVICE_NAME=$PKG_NAME" >> $GITHUB_ENV
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Check space usage
      if: (!cancelled())
      run: df -hT

    - name: Organize files
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        rm $PKG_NAME/_opk/Paladin_funkey-s.opk
        cd $PKG_NAME/_opk
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT
        
    - name: Upload firmware directory
      uses: actions/upload-artifact@main
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: ${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}
        
    - name: Generate release tag
      id: tag
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
        echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
        touch release.txt
        echo "status=success" >> $GITHUB_OUTPUT
        
    - name: Upload firmware to release
      uses: softprops/action-gh-release@v1
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/*.opk
